# Generated by Django 4.2.3 on 2023-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_discipline_title_en_discipline_title_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
