# Generated by Django 4.2.3 on 2023-07-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_person_facebook_person_site_person_twitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', to='server.author', verbose_name='Участники'),
        ),
    ]
