# Generated by Django 4.2.3 on 2023-08-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='files/materials/%Y/%m/%d/', verbose_name='PDF файл'),
        ),
        migrations.AlterField(
            model_name='material',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Ютуб ссылка'),
        ),
    ]
